export const REQUEST_PRODUCTS = "REQUEST_PRODUCTS"
export const SUCCESS_PRODUCTS = "SUCCESS_PRODUCTS"
export const FAIL_PRODUCTS = "FAIL_PRODUCTS"
export const REQUEST_SINGLE_PRODUCTS = "REQUEST_SINGLE_PRODUCTS"
export const SUCCESS_SINGLE_PRODUCTS = "SUCCESS_SINGLE_PRODUCTS"
export const FAIL_SINGLE_PRODUCTS = "FAIL_SINGLE_PRODUCTS"

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST"
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS"
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET"
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL"

export const CLEAR_ERRORS    = "CLEAR_ERRORS   "